title: Katie-May
description: > # this means to ignore newlines until "baseurl:"
  DevOps Engineer working at GitHub
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://katiem0.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Katie May
author-img: katiemay.jpeg 
about-author: DevOps Engineer at GitHub  
social-github: katiem0
social-linkedin: katiemay0


# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]